<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn"%>
<%@ taglib uri="http://www.itcast.cn/babasport" prefix="itcast"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>  
<%@ taglib uri="/WEB-INF/yt-view.tld" prefix="view"%>
<%@page isELIgnored="false"%>
<script language="javascript" src="/shop/js/aa.js"></script>
